### ISSUE TITLE
git.exc.InvalidGitRepositoryError

### ISSUE THREAD

**Issue by bott1eee** [caoyu-noob/Multi-GPT2#3]
Hello! When i ran "python train.py --train_datasets datasets/C......",i had encountered the following problem:

> Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from config import get_trainer_config
  File "D:\papers\Multi-GPT2-main\Multi-GPT2-main\config.py", line 9, in <module>
    repo = git.Repo(search_parent_directories=True)
  File "D:\environment\python\testvitualenv\multigpt2\lib\site-packages\git\repo\base.py", line 220, in __init__
    self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
  File "D:\environment\python\testvitualenv\multigpt2\lib\site-packages\git\repo\base.py", line 303, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

What can i do to solve this problem? thanks!

**Comment by caoyu-noob** [comment]
Maybe your current working directory is not a Git repository. The simplest way is to delete all lines related to "repo" in `config.py`, they are not necessary for running the code.
