### ISSUE TITLE
RuntimeError: _th_gather not supported on CUDAType for Bool

### ISSUE THREAD

**Issue by lyshuang** [caoyu-noob/Multi-GPT2#4]
When I run the experiment as readme, the following error occursed.
Is the version of pytorch really 1.1.0 as stated in requirements.txt？
Traceback (most recent call last):
  File "train.py", line 390, in <module>
    main()
  File "train.py", line 387, in main
    last_checkpoint_path, interrupt_checkpoint_path, log_dir, test_data_type=args.test_data_type)
  File "train.py", line 330, in training_procedure
    raise e
  File "train.py", line 326, in training_procedure
    risk_func=get_risk_metric_func(trainer_config.risk_metric))
  File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 808, in train
    func(epoch)
  File "train.py", line 292, in test_func
    model_trainer.test(metric_funcs, external_metrics_func, epoch)
  File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 790, in test
    self._eval_test(metric_funcs, external_metrics_func, epoch, inference)
  File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 683, in _eval_test
    metrics, metric_funcs, external_metrics_func, i)
  File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 637, in _get_eval_predictions
    predictions = self.model.inference(enc_contexts=enc_contexts)
  File "/home/lys/workspace/Multi-GPT2-main/model/gpt2_model.py", line 1410, in inference
    return self.beam_search(enc_contexts, return_beams, beam_starts)
  File "/home/lys/workspace/Multi-GPT2-main/model/gpt2_model.py", line 1540, in beam_search
    is_end = torch.gather(is_end, 1, beam_idxs)
RuntimeError: _th_gather not supported on CUDAType for Bool

**Comment by caoyu-noob** [comment]
Sorry, I just updated the code and I forgot to update "requirements.txt". I used pytorch==1.5.0 in the new code.

**Comment by lyshuang** [comment]
OK, I got it.Thanks.

**Comment by lyshuang** [comment]
I'm sorry to bother you again. But I run the code after changing the version of pytorch to 1.5.0,
an error occurred as follows when the test was completed for evaluation.
can you tell me how to solve this problem? Thanks.


&nbsp;Can't locate Sort/Naturally.pm in @INC (you may need to install the Sort::Naturally module) ***@***.*** contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at metrics/mteval-v14c.pl line 8.
BEGIN failed--compilation aborted at metrics/mteval-v14c.pl line 8.
mteval-v14c.pl returns unexpected message
cmd = ['perl', 'metrics/mteval-v14c.pl', '-s', 'runs/Sep07_16-20-26_gpt2_persona_mean_sm_sa/src.xml', '-t', 'runs/Sep07_16-20-26_gpt2_persona_mean_sm_sa/hyp.xml', '-r', 'runs/Sep07_16-20-26_gpt2_persona_mean_sm_sa/ref.xml']


Traceback (most recent call last):
&nbsp; File "/home/lys/workspace/Multi-GPT2-main/new_metrics.py", line 63, in calc_nist_bleu
&nbsp; &nbsp; nist_score = lines[-22].strip('\r').split()[3]
IndexError: list index out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "train.py", line 390, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "train.py", line 387, in main
&nbsp; &nbsp; last_checkpoint_path, interrupt_checkpoint_path, log_dir, test_data_type=args.test_data_type)
&nbsp; File "train.py", line 330, in training_procedure
&nbsp; &nbsp; raise e
&nbsp; File "train.py", line 326, in training_procedure
&nbsp; &nbsp; risk_func=get_risk_metric_func(trainer_config.risk_metric))
&nbsp; File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 808, in train
&nbsp; &nbsp; func(epoch)
&nbsp; File "train.py", line 292, in test_func
&nbsp; &nbsp; model_trainer.test(metric_funcs, external_metrics_func, epoch)
&nbsp; File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 790, in test
&nbsp; &nbsp; self._eval_test(metric_funcs, external_metrics_func, epoch, inference)
&nbsp; File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 689, in _eval_test
&nbsp; &nbsp; external_metrics = external_metrics_func(full_references, full_predictions, epoch, is_best)
&nbsp; File "train.py", line 244, in external_metrics_func
&nbsp; &nbsp; rouge_l, f1_score, avg_length = nlp_metrics(references_file_path, predictions_file_path, root_path=log_dir)
&nbsp; File "/home/lys/workspace/Multi-GPT2-main/new_metrics.py", line 565, in nlp_metrics
&nbsp; &nbsp; nist, nist_bleu, nist_list, nist_bleu_list = calc_nist_bleu([ref_file], pred_file, fld_out=root_path)
&nbsp; File "/home/lys/workspace/Multi-GPT2-main/new_metrics.py", line 73, in calc_nist_bleu
&nbsp; &nbsp; print(error.decode())
AttributeError: 'NoneType' object has no attribute 'decode'




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caoyu-noob/Multi-GPT2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月4日(星期六) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [caoyu-noob/Multi-GPT2] RuntimeError: _th_gather not supported on CUDAType for Bool (#4)





 
Sorry, I just updated the code and I forgot to update "requirements.txt". I used pytorch==1.5.0 in the new code.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caoyu-noob** [comment]
Sorry for late. It should be some problems related to the Perl packages.
Seems that you do not install the Sort::Naturally package for Perl.
You can use cpanminus to install following packages
`cpanm XML::Twig`
`cpanm Sort::Naturally`
`cpanm String::Util`

**Comment by lyshuang** [comment]
Thank you very much, I solved the previous problem after installing related packages. 
Unfortunately，end training on epoch 5, and start testing , the fllowing problem appeared.
I found there is no "best model" under the run folder.
I'm sorry to bother you again.

`09/08/2021 21:01:42 - INFO - root -   Loading the best model...
Traceback (most recent call last):
  File "train.py", line 390, in <module>
    main()
  File "train.py", line 387, in main
    last_checkpoint_path, interrupt_checkpoint_path, log_dir, test_data_type=args.test_data_type)
  File "train.py", line 330, in training_procedure
    raise e
  File "train.py", line 326, in training_procedure
    risk_func=get_risk_metric_func(trainer_config.risk_metric))
  File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 816, in train
    func(-1)
  File "train.py", line 292, in test_func
    model_trainer.test(metric_funcs, external_metrics_func, epoch)
  File "/home/lys/workspace/Multi-GPT2-main/model/trainer.py", line 793, in test
    state_dict = torch.load(self.best_model_path, map_location=self.device)
  File "/home/lys/.virtualenvs/multi-gp2/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/lys/.virtualenvs/multi-gp2/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/lys/.virtualenvs/multi-gp2/lib/python3.7/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/Sep08_20-51-22_gpt2_persona_mean_sm_sa/best_model'
`

**Comment by caoyu-noob** [comment]
Seems that training on the dummy data does not obtain a lower PPL than the initial one, so no `best_model` is saved.
I have updated the code to set a higher threshold.

**Comment by lyshuang** [comment]
Thank you for updating the code, and I trained model successfully.
But inferenced, the following error occurred.

`Traceback (most recent call last):
  File "inference.py", line 293, in <module>
    main()
  File "inference.py", line 260, in main
    uncertainty_loss=args.uncertainty_loss)
TypeError: __init__() got an unexpected keyword argument 'train_batch_size'`

And I found the parameters of `variable Trainer line 239 in inference.py` are inconsistend with 44 line `__init__ definitions in /model/trainer.py`

`line 239 inference.py`
`    trainer = Trainer(model,
                      valid_dataset,
                      None,
                      logger=logger,
                      valid_dataset=valid_dataset,
                      test_dataset=test_dataset,
                      train_batch_size=trainer_config.train_batch_size,
                      batch_split=trainer_config.batch_split,
                      test_batch_size=trainer_config.test_batch_size,
                      single_input=args.single_input,
                      n_jobs=trainer_config.n_jobs,
                      clip_grad=trainer_config.clip_grad,
                      device=device,
                      ignore_idxs=tokenizer.all_special_ids,
                      local_rank=args.local_rank,
                      apex_level=None,
                      apex_loss_scale=trainer_config.apex_loss_scale,
                      linear_schedule=trainer_config.linear_schedule,
                      n_epochs=trainer_config.n_epochs,
                      evaluate_full_sequences=trainer_config.evaluate_full_sequences,
                      full_input=trainer_config.full_input,
                      uncertainty_loss=args.uncertainty_loss)`

`45 line /model/trainer.py`
`    def __init__(self, model, train_dataset, trainer_config, writer, logger=None, test_dataset=None, valid_dataset=None,
                 n_jobs=0, label_smoothing=0, device=torch.device('cuda'), ignore_idxs=[], local_rank=-1,
                 apex_level=None, apex_loss_scale=None, evaluate_full_sequences=False, full_input=False,
                 max_length=511, max_y_length=80, uncertainty_loss=False, new_dataset=False, best_model_path='',
                 extra_module_lr_rate=1, no_persona=False, pointer_gen=False):`

**Comment by caoyu-noob** [comment]
Seems that I forgot to update `trainer` in `inference.py`. I have fixed the bug.
Besides, I do not recommend using the model trained on dummy data for inference. It may always generate empty responses, which can cause errors during evaluation using auto metrics.

**Comment by caoyu-noob** [comment]
Seems that I forgot to update `trainer` in `inference.py`. I have fixed the bug.
Besides, I do not recommend using the model trained on dummy data for inference. It may always generate empty responses, which can cause errors during evaluation using auto metrics.
